right_mobile_gello_node:
  ros__parameters:
    id: right_mobile
    port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT8ISEQG-if00-port0 # Set to a specific port if needed
    type: single
    mirror': False

right_xarm_node:
  ros__parameters:
    xARM_IP: "192.168.1.228"
    id: right_mobile
    testing: True

leap_v1_node_right:
  ros__parameters:
    port: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTA2U2IO-if00-port0"
    isLeft: False

leap_v1_ik_right:
  ros__parameters:
    isLeft: False
    useViewer: True

leap_v2_ik_right:
  ros__parameters:
    isLeft: False

palm_camera_node:
  ros__parameters:
    cameras: [
        # left_thumb,
        # left_pinky,
        right_thumb,
        right_pinky,
      ]
    serials: ["00020", "00021"] # left_thumb, left_pinky, right_thumb, right_pinky
    fourcc: MJPG
    width: 320
    height: 240
    fps: 60
    superwide: True

glove_node:
  ros__parameters:
    left_glove_sn: "45a7fc8f"
    right_glove_sn: "8569617b"

data_sync_node:
  ros__parameters:
    topics: [
        "/right/thumb_camera_im",
        "/right/pinky_camera_im",
        # "/zed/im",
        # "/glove/r_short",
        # "/glove/r_full",
        /arm/right_mobile/obs_eef_pose,
        # /leaphand_node/cmd_allegro_right,
        # /leapv2_node/cmd_raw_leap_r,
      ]
    rosbag_collect: False
    collect_data_mode: False
