right_mobile_gello_node:
  ros__parameters:
    id: right_mobile
    port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT8ISEQG-if00-port0 # Set to a specific port if needed

right_xarm_node:
  ros__parameters:
    xarm_ip: "192.168.1.228"
    arm_id: right_mobile
    teleop: True
    use_rmp: False

leap_v2_node_right:
  ros__parameters:
    port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT78LTIG-if00-port0
    isLeft: False

leap_v2_ik_right:
  ros__parameters:
    isLeft: False

palm_camera_node:
  ros__parameters:
    cameras: [
        # left_thumb,
        # left_pinky,
        right_thumb,
        right_pinky,
      ]
    serials: ["00010", "00001"] # left_thumb, left_pinky, right_thumb, right_pinky
    fourcc: MJPG
    width: 320
    height: 240
    fps: 60
    superwide: True

glove_node:
  ros__parameters:
    left_glove_sn: "60f3738b"
    right_glove_sn: "431ea0a1"

zed_node:
  ros__parameters:
    serial: 16352271 #13909734
    which_hands: [""]
    visualize: False
    zed_live: True # run when running on the robot

ticker_node:
  ros__parameters:
    rate: 30.0

data_sync_node:
  ros__parameters:
    topics:
      [
        "/right/thumb_camera_im",
        "/right/pinky_camera_im",
        "/glove/r_short",
        /arm/right_mobile/obs_eef_pose,
        /leapv2_node/cmd_raw_leap_r,
        "/ticker",
      ]
    rosbag_collect: False
    collect_data_mode: True
